docs: docs/
readme: README.md
fish: fish/
tmux: tmux/tmux.conf
scripts: scripts/
kitty: kitty/
hammerspoon: hammerspoon/
vim: nvim/
paths: config-paths.yml
ignore: .ignore
codespell: codespell/custom_dict.txt
ssh: .ssh/config
wezterm: wezterm/
cbfmt: cbfmt.toml
home: home-manager/
nix: nix/nix.conf
git: home-manager/modules/git.nix
bat: home-manager/modules/bat.nix
starship: home-manager/modules/starship.nix
atuin: home-manager/modules/atuin.nix
topgrade: home-manager/modules/topgrade.nix
