format = """
 $directory$git_branch$git_status
 $character """

[character] # colors from ~/.config/kitty/lighthaus-theme.conf
success_symbol = "[ğŸ…¸](bold #00BFA4)"
error_symbol = "[ğŸ…¸](bold #FF5050)"
vicmd_symbol = "[ğŸ…½](bold #44B273)"
vimcmd_replace_one_symbol = "[ğŸ†](bold #D16BB7)"
vimcmd_replace_symbol = "[ğŸ†](bold #D16BB7)"
vimcmd_visual_symbol = "[ğŸ†…](bold #FFFF00)"

[git_branch]
symbol = "îœ‚ "
style = "bold #f74e27" # git brand color
format = "[$symbol$branch(:$remote_branch)]($style) "

[directory]
read_only = " ï ½"
