format = """
 $directory$custom$git_branch$git_status
 $character """

right_format = "$cmd_duration"

[character] # colors from ~/.config/kitty/lighthaus-theme.conf
success_symbol = "[ðŸ…¸ ](bold #89ca78)"
error_symbol = "[ðŸ…¸ ](bold #ef596f)"
vicmd_symbol = "[ðŸ…½ ](bold #89ca78)"
vimcmd_replace_one_symbol = "[ðŸ† ](bold #d55fde)"
vimcmd_replace_symbol = "[ðŸ† ](bold #d55fde)"
vimcmd_visual_symbol = "[ðŸ†… ](bold #e5c07b)"

[custom.gitlab_icon]
description = 'Show a GitLab or GitHub icon depending on current git remote'
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
command = 'GIT_REMOTE=$(git ls-remote --get-url 2> /dev/null); if [[ "$GIT_REMOTE" =~ "github" ]]; then printf "\e[1;37mï‚›\e[0m"; elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then echo "ïŠ–"; else echo "ó°Š¢"; fi'
shell = ["bash", "--noprofile", "--norc"]
style = "bold #f74e27" # git brand color
format = '[$output]($style)  '

[git_branch]
symbol = ""
style = "bold #f74e27" # git brand color
format = "[$symbol$branch(:$remote_branch)]($style) "

[cmd_duration]
format = "[ï€— $duration]($style)"
style = "bold #586068"

[directory]
read_only = " ó°Œ¾"
